#!/bin/bash
# Go to home directory
cd ~
VERSION_NUM=5.0.1

# You can change what anaconda version you want at 
# https://repo.continuum.io/archive/
wget https://repo.continuum.io/archive/Anaconda2-$VERSION_NUM-Linux-x86_64.sh
bash Anaconda2-$VERSION_NUM-Linux-x86_64.sh -b -p ~/anaconda
rm Anaconda2-$VERSION_NUM-Linux-x86_64.sh
echo 'export PATH="~/anaconda/bin:$PATH"' >> ~/.bashrc 

# Refresh basically
source .bashrc

conda update conda
